# Generated by Django 4.2.20 on 2025-05-14 09:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_table_number_alter_table_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
